"""EP2 — lista de trechos (EDL) seguindo o roteiro. Tempos aproximados da fonte + primeiras/últimas palavras esperadas;
refinar.py acha o corte exato em cada trecho. yt=True: só na versão do YouTube (trecho exclusivo)."""

# (fonte, início aprox., fim aprox., primeiras palavras, últimas palavras, yt)
EDL = [
    # ---------------------------------------------------------------- abertura
    ("lado_inicio", 5.5, 10.3, "se o instagram acabasse", "sentiria falta", False),
    ("take1", 10.6, 13.2, "quem você procuraria", "outro lugar", False),
    ("take1", 13.7, 14.7, "vamos deep", "vamos deep", False),          # + "Vamo de DEEP?" + vinheta
    ("take1", 16.1, 19.6, "você pensou em alguém", "guarda esse nome", False),
    # ---------------------------------------------------------------- cap. 1 — a busca
    ("take1", 23.6, 28.8, "eu comecei a pensar", "aconteceu em mim", False),
    ("take1", 28.5, 36.9, "porque eu comecei a procurar", "podcasts", False),
    ("take1", 41.2, 62.9, "um tipo de conversa", "tinha ficado", False),
    ("take1", 76.2, 83.8, "e essa busca me fez pensar também", "queria produzir", False),
    ("take1", 84.2, 120.8, "porque eu trabalho com internet", "conversa até o final", False),
    ("take1", 149.6, 184.4, "e conversando com amigas", "quem o acompanha", False),
    ("take1", 185.0, 210.4, "e a minha leitura disso", "papéis diferentes", False),
    ("take1", 218.2, 226.8, "então um pode despertar", "ideia por exemplo", False),
    ("take1", 227.0, 233.1, "e isso ajuda a explicar", "por outros lugares", False),
    ("take1", 265.0, 274.7, "a gente também quer poder", "aprofundar sobre isso", False),
    # ---------------------------------------------------------------- cap. 2 — descobrir x compreender (YouTube)
    ("take1", 279.7, 305.1, "e tem uma diferença", "chegaram às conclusões", True),
    ("take1", 306.1, 310.1, "porque às vezes", "falta é contexto", True),
    ("take1", 310.4, 325.9, "o que aconteceu antes", "para dividir aqui", True),
    ("take1", 372.3, 400.6, "e eu encontrei uma sobre podcasts", "longo para ser bom", True),
    ("take1", 415.5, 426.7, "significa que algumas conversas", "possíveis contradições", True),
    ("take1", 427.8, 480.0, "para quem cria", "mais tempo num assunto", True),
    # ---------------------------------------------------------------- cap. 3 — faturar x construir
    ("take2", 0.4, 7.4, "e foi dessa vontade", "nasceu o deep", False),
    ("take2", 18.0, 38.8, "e isso tem tudo a ver", "aqui no instagram", False),
    ("take2", 39.3, 53.3, "para quem entra nesse mercado", "primeiro contrato", False),
    ("take2", 74.4, 101.9, "mas depois aparece outra pergunta", "acompanhar você", False),
    ("take2", 102.3, 119.3, "e é aí que a conversa", "quem te acompanha", False),
    ("take2", 125.0, 131.4, "e o motivo que você dá", "para te assistir", False),
    ("take2", 146.1, 174.9, "lembrando que uma campanha envolve", "no que você faz", False),
    ("take2", 175.3, 181.0, "essa pergunta começou", "tão grande para mim", False),
    ("take2", 208.1, 222.8, "o que eu quero desenvolver", "procurar o meu conteúdo", False),
    # ---------------------------------------------------------------- cap. 4 — mais caminhos, mesma dependência
    ("take2", 231.3, 232.8, "hoje existem", "hoje existem", False),
    ("take2", 236.0, 256.9, "mais caminhos para transformar", "fechar parcerias", False),
    ("take2", 256.7, 259.5, "só que", "só que", False),
    ("take2", 268.5, 283.0, "ter mais possibilidades de receita", "na distribuição", False),
    ("take2", 293.6, 296.9, "nos formatos", "que seguir", False),
    ("take2", 297.3, 307.5, "e eu realmente não queria", "feed de alguém", False),
    ("take2", 326.8, 334.0, "foi dessa vontade que", "criei um guia", False),
    ("take2", 348.3, 359.3, "e estou tentando cada vez mais", "tem por aqui", False),
    ("take2", 359.7, 381.5, "só que vamos lá", "pode ser cancelada", False),
    ("take2", 381.3, 383.3, "e estar em vários lugares", "em vários lugares", True),
    ("take2", 387.8, 390.1, "também tem um custo", "tem um custo", True),
    ("take2", 393.7, 413.0, "imagina que cada canal", "sustentar tá", True),
    ("take2", 456.6, 469.7, "então antes de abrir", "por aquele caminho", True),
    ("take2", 470.1, 504.0, "um podcast pode dar espaço", "a mesma coisa tá", True),
    ("take2", 506.0, 509.5, "uma lista de", "por exemplo", True),
    ("take2", 517.9, 535.6, "pode permitir continuar", "abrir a mensagem", True),
    ("take3", 0.2, 20.8, "você ganha uma possibilidade", "de quem acompanha", True),
    # ---------------------------------------------------------------- cap. 5 — o que é construir
    ("take3", 23.1, 35.5, "a pessoa precisa encontrar", "onde publicar", False),
    ("take3", 41.7, 48.7, "a pergunta é", "rotina de alguém", False),
    ("take3", 79.5, 88.0, "para mim é aí que construir", "mais concreto", False),
    ("take3", 88.7, 108.3, "porque é desenvolver", "formato muda", False),
    ("take3", 108.4, 118.4, "olha eu ainda estou", "dentre muitas outras", False),
    ("take3", 122.9, 125.6, "que faz parte", "desse processo", False),
    ("take3", 126.1, 132.0, "e com certeza ela vem", "próxima edição", False),
    ("take3", 138.6, 143.2, "então lembra do nome", "começo do episódio", False),
    ("take3", 157.1, 166.8, "talvez você procure essa pessoa", "uma história", False),
    ("take3", 177.3, 188.6, "existe um motivo", "construir também", False),
    ("take3", 189.1, 205.6, "porque gente o faturamento", "reputação que forma", False),
    ("take3", 215.8, 221.4, "e nos motivos que você dá", "continuar voltando", False),
    ("take3", 221.4, 228.7, "só que essa relação", "mais complexa", False),
    ("take3", 232.2, 237.2, "porque com mais ferramentas", "produzir conteúdo", False),
    ("take3", 237.7, 244.7, "mais facilidade para vender", "nossa atenção", False),
    ("take3", 248.0, 253.4, "e aí", "vamos conseguir", False),
    ("take3", 257.5, 265.0, "decidir em quem confiar", "em quem confiar", False),
    ("take3", 265.5, 269.9, "e é sobre isso", "último episódio", False),
    ("take3", 270.7, 271.2, "tchau", "tchau", False),
]
